<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\PartyBundle;
use App\Models\PartyBundleItem;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Create Default Users (Vendor Admin & Consumers)
        $vendor = User::factory()->create([
            'name' => 'Gwallameji Vendor Admin',
            'email' => 'admin@booze.test',
            'password' => bcrypt('password'),
            'role' => 'vendor_admin',
            'phone' => '09031704109',
            'store_name' => 'Gwallameji Central Liquor Store',
        ]);

        $vendorAlt = User::factory()->create([
            'name' => 'Vendor Account (Legacy)',
            'email' => 'vendor@booze.test',
            'password' => bcrypt('password'),
            'role' => 'vendor_admin',
            'phone' => '08039998877',
            'store_name' => 'Bauchi Premium Drinks Depot',
        ]);

        $consumer1 = User::factory()->create([
            'name' => 'John Student',
            'email' => 'consumer@booze.test',
            'password' => bcrypt('password'),
            'role' => 'consumer',
            'phone' => '08069876543',
            'store_name' => null,
        ]);

        $consumer2 = User::factory()->create([
            'name' => 'Amina Bauchi',
            'email' => 'amina@booze.test',
            'password' => bcrypt('password'),
            'role' => 'consumer',
            'phone' => '08051112233',
            'store_name' => null,
        ]);

        // 2. Create Categories
        $beers = Category::create([
            'name' => 'Beers',
            'slug' => 'beers',
            'icon' => 'Beer',
            'description' => 'Cold lagers, stouts, and malt beverages',
        ]);

        $spirits = Category::create([
            'name' => 'Spirits',
            'slug' => 'spirits',
            'icon' => 'Flame',
            'description' => 'Whiskey, vodka, gin, cognac, and bitters',
        ]);

        $wines = Category::create([
            'name' => 'Wines',
            'slug' => 'wines',
            'icon' => 'Wine',
            'description' => 'Fine red, white, sparkling, and sweet wines',
        ]);

        $mixers = Category::create([
            'name' => 'Mixers',
            'slug' => 'mixers',
            'icon' => 'CupSoda',
            'description' => 'Sodas, tonic water, and energy drinks',
        ]);

        // 3. Nigerian Brands Product Catalog (20+ per category)
        $catalog = [
            // ==================== 1. BEERS & MALTS (20 Products) ====================
            [
                'category_id' => $beers->id,
                'name' => 'Trophy Extra Quality Lager (600ml)',
                'unit' => 'bottle',
                'cost_price' => 650.00,
                'selling_price' => 850.00,
                'stock_level' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=600&q=80',
                'description' => 'The Honourable Lager. Crisp and refreshing Nigerian lager.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Star Larger Beer (600ml)',
                'unit' => 'bottle',
                'cost_price' => 650.00,
                'selling_price' => 850.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=600&q=80',
                'description' => 'Shine on with classic Nigerian Star Lager.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Guinness Extra Stout (600ml)',
                'unit' => 'bottle',
                'cost_price' => 850.00,
                'selling_price' => 1100.00,
                'stock_level' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1567696911980-2eed69a46042?auto=format&fit=crop&w=600&q=80',
                'description' => 'Rich, dark, roasted malt taste of Guinness Stout.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Goldberg Premium Lager (600ml)',
                'unit' => 'bottle',
                'cost_price' => 650.00,
                'selling_price' => 850.00,
                'stock_level' => 45,
                'image_url' => 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?auto=format&fit=crop&w=600&q=80',
                'description' => 'Your culture, your beer. Golden brewed premium lager.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Hero Premium Lager (600ml)',
                'unit' => 'bottle',
                'cost_price' => 650.00,
                'selling_price' => 850.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1584225064785-c62a8b43d148?auto=format&fit=crop&w=600&q=80',
                'description' => 'Opa. Premium brewed quality lager beer.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Life Continental Lager (600ml)',
                'unit' => 'bottle',
                'cost_price' => 650.00,
                'selling_price' => 850.00,
                'stock_level' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1571613316887-6f8d5cbf7ef7?auto=format&fit=crop&w=600&q=80',
                'description' => 'Progressive lager brewed for true refreshment.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Gulder Ultimate Lager (600ml)',
                'unit' => 'bottle',
                'cost_price' => 700.00,
                'selling_price' => 900.00,
                'stock_level' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1566633806327-68e1deed5b97?auto=format&fit=crop&w=600&q=80',
                'description' => 'The Ultimate Beer. Crisp, bitter, and bold.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Legend Extra Stout (600ml)',
                'unit' => 'bottle',
                'cost_price' => 800.00,
                'selling_price' => 1050.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Full-bodied dark stout beer.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Heineken Premium Lager (600ml)',
                'unit' => 'bottle',
                'cost_price' => 900.00,
                'selling_price' => 1200.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?auto=format&fit=crop&w=600&q=80',
                'description' => 'International premium Dutch lager brewed in Nigeria.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Budweiser King of Beers (600ml)',
                'unit' => 'bottle',
                'cost_price' => 850.00,
                'selling_price' => 1100.00,
                'stock_level' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1528823872057-9c018a7a70b3?auto=format&fit=crop&w=600&q=80',
                'description' => 'King of Beers. Smooth beechwood-aged lager.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Orijin Herbal Beer (600ml)',
                'unit' => 'bottle',
                'cost_price' => 750.00,
                'selling_price' => 950.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Herbal alcoholic drink blended with African spices.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Smirnoff Ice Double Black (330ml Can)',
                'unit' => 'can',
                'cost_price' => 750.00,
                'selling_price' => 1000.00,
                'stock_level' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
                'description' => 'Strong guarana-infused vodka beverage.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Desperados Tequila Flavoured Beer (330ml)',
                'unit' => 'bottle',
                'cost_price' => 850.00,
                'selling_price' => 1100.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1518176258614-4584ee237ce2?auto=format&fit=crop&w=600&q=80',
                'description' => 'Wild tequila-flavoured beer with citrus kick.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Flying Fish Passion Fruit Beer (330ml)',
                'unit' => 'bottle',
                'cost_price' => 700.00,
                'selling_price' => 900.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=600&q=80',
                'description' => 'Refreshing passion-fruit flavoured lager.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Trophy Stout (600ml)',
                'unit' => 'bottle',
                'cost_price' => 750.00,
                'selling_price' => 1000.00,
                'stock_level' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1567696911980-2eed69a46042?auto=format&fit=crop&w=600&q=80',
                'description' => 'Extra dark roasted malt stout beer.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Malta Guinness (330ml Can)',
                'unit' => 'can',
                'cost_price' => 350.00,
                'selling_price' => 500.00,
                'stock_level' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=600&q=80',
                'description' => 'Non-alcoholic premium malt drink packed with B-vitamins.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Amstel Malta Ultra (330ml Can)',
                'unit' => 'can',
                'cost_price' => 350.00,
                'selling_price' => 500.00,
                'stock_level' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?auto=format&fit=crop&w=600&q=80',
                'description' => 'Low sugar premium non-alcoholic malt drink.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Maltina Classic (330ml Can)',
                'unit' => 'can',
                'cost_price' => 350.00,
                'selling_price' => 500.00,
                'stock_level' => 70,
                'image_url' => 'https://images.unsplash.com/photo-1584225064785-c62a8b43d148?auto=format&fit=crop&w=600&q=80',
                'description' => 'Sharing happiness. Nourishing malt drink.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Dubic Malt (330ml Can)',
                'unit' => 'can',
                'cost_price' => 300.00,
                'selling_price' => 450.00,
                'stock_level' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1571613316887-6f8d5cbf7ef7?auto=format&fit=crop&w=600&q=80',
                'description' => 'Rich, wholesome non-alcoholic malt beverage.',
            ],
            [
                'category_id' => $beers->id,
                'name' => 'Grand Malt (330ml Can)',
                'unit' => 'can',
                'cost_price' => 300.00,
                'selling_price' => 450.00,
                'stock_level' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1566633806327-68e1deed5b97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Energetic non-alcoholic malt drink.',
            ],

            // ==================== 2. SPIRITS & BITTERS (20 Products) ====================
            [
                'category_id' => $spirits->id,
                'name' => 'Orijin Herbal Bitters (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2600.00,
                'selling_price' => 3500.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Famous African herbal bitters crafted with roots and herbs.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Action Bitters (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2000.00,
                'selling_price' => 2800.00,
                'stock_level' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Popular herbal bitters spirit drink.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Alomo Bitters (75cl)',
                'unit' => 'bottle',
                'cost_price' => 1800.00,
                'selling_price' => 2500.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
                'description' => 'Original traditional herbal bitters.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Odogwu Bitters (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2400.00,
                'selling_price' => 3200.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Premium herbal bitters drink with ginger and honey.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => "Seaman's Aromatic Schnapps (75cl)",
                'unit' => 'bottle',
                'cost_price' => 3500.00,
                'selling_price' => 4500.00,
                'stock_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
                'description' => 'The traditional blessing schnapps spirit.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Best Dark Rum (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2800.00,
                'selling_price' => 3800.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Smooth aged dark rum for mixing or sipping.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Chelsea Dry Gin (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2200.00,
                'selling_price' => 3000.00,
                'stock_level' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Classic London-style dry gin distilled in Nigeria.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => "Lord's Dry Gin (75cl)",
                'unit' => 'bottle',
                'cost_price' => 2600.00,
                'selling_price' => 3500.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
                'description' => 'Premium London dry gin for distinguished tastes.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Squadron Dark Rum (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2400.00,
                'selling_price' => 3200.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Rich Caribbean style dark rum.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Campari Aperitif (75cl)',
                'unit' => 'bottle',
                'cost_price' => 11500.00,
                'selling_price' => 14500.00,
                'stock_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Iconic red Italian bitter aperitif.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Hennessy Very Special Cognac (70cl)',
                'unit' => 'bottle',
                'cost_price' => 42000.00,
                'selling_price' => 48000.00,
                'stock_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Premium French Cognac with toasted oak and fruitiness.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Martell VS Single Distillery (70cl)',
                'unit' => 'bottle',
                'cost_price' => 36000.00,
                'selling_price' => 42000.00,
                'stock_level' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
                'description' => 'Rich cognac distilled from single grape source.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Jameson Triple Distilled Irish Whiskey (70cl)',
                'unit' => 'bottle',
                'cost_price' => 18000.00,
                'selling_price' => 22000.00,
                'stock_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
                'description' => 'Smooth Irish whiskey triple distilled for taste.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => "Jack Daniel's Old No.7 Tennessee Whiskey (70cl)",
                'unit' => 'bottle',
                'cost_price' => 23000.00,
                'selling_price' => 28000.00,
                'stock_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Charcoal-mellowed Tennessee whiskey.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Johnnie Walker Black Label (75cl)',
                'unit' => 'bottle',
                'cost_price' => 26000.00,
                'selling_price' => 32000.00,
                'stock_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
                'description' => '12-year-old blended Scotch whiskey with smoky finish.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Johnnie Walker Red Label (75cl)',
                'unit' => 'bottle',
                'cost_price' => 14000.00,
                'selling_price' => 18000.00,
                'stock_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Dynamic blended Scotch whiskey.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => "McDowell's No.1 Luxury Whiskey (75cl)",
                'unit' => 'bottle',
                'cost_price' => 5000.00,
                'selling_price' => 6500.00,
                'stock_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Popular smooth blended whiskey.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Baileys Original Irish Cream (75cl)',
                'unit' => 'bottle',
                'cost_price' => 13000.00,
                'selling_price' => 16500.00,
                'stock_level' => 18,
                'image_url' => 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
                'description' => 'Creamy liqueur with Irish whiskey and cocoa.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Sierra Tequila Reposado (70cl)',
                'unit' => 'bottle',
                'cost_price' => 15500.00,
                'selling_price' => 19500.00,
                'stock_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Aged Mexican tequila with Sombrero cap.',
            ],
            [
                'category_id' => $spirits->id,
                'name' => 'Smirnoff Triple Distilled Vodka (75cl)',
                'unit' => 'bottle',
                'cost_price' => 7500.00,
                'selling_price' => 9500.00,
                'stock_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Classic pure vodka for cocktails.',
            ],

            // ==================== 3. WINES (20 Products) ====================
            [
                'category_id' => $wines->id,
                'name' => 'Carlo Rossi Sweet Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 5200.00,
                'selling_price' => 6500.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'California sweet red wine with rich fruity aromas.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Four Cousins Sweet Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 4500.00,
                'selling_price' => 5800.00,
                'stock_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'South African sweet red table wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => '4th Street Sweet Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 4000.00,
                'selling_price' => 5200.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Fresh, fruity sweet red wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Baron de Valls Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 3500.00,
                'selling_price' => 4500.00,
                'stock_level' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'Spanish smooth red wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Veuve du Vernay Ice Sparkling Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 9500.00,
                'selling_price' => 12500.00,
                'stock_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'French sparkling wine best served over ice.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Andre Cellars Sparkling Pink Moscato (75cl)',
                'unit' => 'bottle',
                'cost_price' => 7800.00,
                'selling_price' => 9800.00,
                'stock_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'Delightful pink sparkling wine with sweet citrus notes.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Chamdor Non-Alcoholic Sparkling Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2600.00,
                'selling_price' => 3500.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Sparkling grape juice drink for celebrations.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Agor Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 5400.00,
                'selling_price' => 6800.00,
                'stock_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'Sweet communion and dinner red wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Robertson Winery Sweet Red (75cl)',
                'unit' => 'bottle',
                'cost_price' => 4800.00,
                'selling_price' => 6200.00,
                'stock_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Smooth and fruity South African red wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'JP Chenet Delicious Medium Sweet Red (75cl)',
                'unit' => 'bottle',
                'cost_price' => 5800.00,
                'selling_price' => 7500.00,
                'stock_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'French red wine in curved bottle.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Frontera Cabernet Sauvignon Red (75cl)',
                'unit' => 'bottle',
                'cost_price' => 5500.00,
                'selling_price' => 7000.00,
                'stock_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Chilean dry red wine with berry notes.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Tall Horse Merlot Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 6000.00,
                'selling_price' => 7800.00,
                'stock_level' => 18,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'Plum and vanilla notes Merlot wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Saint Celine Sweet Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 3600.00,
                'selling_price' => 4800.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Easy-drinking sweet red wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Eva Sparkling Fruit Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2400.00,
                'selling_price' => 3200.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'Fruity non-alcoholic red grape wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Casteller Cava Brut Sparkling (75cl)',
                'unit' => 'bottle',
                'cost_price' => 6800.00,
                'selling_price' => 8500.00,
                'stock_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Spanish Cava dry sparkling wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Don Morris Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 3200.00,
                'selling_price' => 4200.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'Aromatic sweet red dinner wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Martinellis Gold Medal Sparkling Cider (75cl)',
                'unit' => 'bottle',
                'cost_price' => 4200.00,
                'selling_price' => 5500.00,
                'stock_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Premium 100% sparkling apple cider.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'J&W Sparkling White Grape Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 2800.00,
                'selling_price' => 3800.00,
                'stock_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'Non-alcoholic sparkling white wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Nederburg Pinotage Red Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 7500.00,
                'selling_price' => 9500.00,
                'stock_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'description' => 'South African Pinotage red wine.',
            ],
            [
                'category_id' => $wines->id,
                'name' => 'Carlo Rossi Moscato White Wine (75cl)',
                'unit' => 'bottle',
                'cost_price' => 5400.00,
                'selling_price' => 6800.00,
                'stock_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                'description' => 'Sweet white wine with peach aromas.',
            ],

            // ==================== 4. MIXERS & SOFT DRINKS (20 Products) ====================
            [
                'category_id' => $mixers->id,
                'name' => 'Coca-Cola Original (50cl Pet)',
                'unit' => 'bottle',
                'cost_price' => 200.00,
                'selling_price' => 300.00,
                'stock_level' => 150,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Original classic Coca-Cola soft drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Pepsi Cola (50cl Pet)',
                'unit' => 'bottle',
                'cost_price' => 200.00,
                'selling_price' => 300.00,
                'stock_level' => 120,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Refreshing cola beverage.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Sprite Lemon-Lime (50cl Pet)',
                'unit' => 'bottle',
                'cost_price' => 200.00,
                'selling_price' => 300.00,
                'stock_level' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Crisp lemon-lime soda mixer.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Fanta Orange (50cl Pet)',
                'unit' => 'bottle',
                'cost_price' => 200.00,
                'selling_price' => 300.00,
                'stock_level' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Fruity orange flavoured carbonated drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Schweppes Tonic Water (33cl Can)',
                'unit' => 'can',
                'cost_price' => 320.00,
                'selling_price' => 450.00,
                'stock_level' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Classic Indian tonic water mixer for gin and spirits.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Schweppes Bitter Lemon (33cl Can)',
                'unit' => 'can',
                'cost_price' => 320.00,
                'selling_price' => 450.00,
                'stock_level' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Zesty bitter lemon mixer.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Fearless Energy Drink - Red Berry (50cl)',
                'unit' => 'bottle',
                'cost_price' => 280.00,
                'selling_price' => 400.00,
                'stock_level' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Charged red berry energy drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Fearless Energy Drink - Original (50cl)',
                'unit' => 'bottle',
                'cost_price' => 280.00,
                'selling_price' => 400.00,
                'stock_level' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Original energizing taste drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Climax Herbal Energy Drink (33cl Can)',
                'unit' => 'can',
                'cost_price' => 350.00,
                'selling_price' => 500.00,
                'stock_level' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Herbal power energy drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Red Bull Energy Drink (250ml Can)',
                'unit' => 'can',
                'cost_price' => 900.00,
                'selling_price' => 1200.00,
                'stock_level' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Gives you wings. Premium taurine energy drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Predator Energy Drink (50cl Pet)',
                'unit' => 'bottle',
                'cost_price' => 250.00,
                'selling_price' => 350.00,
                'stock_level' => 90,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Fierce energy drink boost.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Monster Energy Drink Original (50cl Can)',
                'unit' => 'can',
                'cost_price' => 1000.00,
                'selling_price' => 1400.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Unleash the Beast high energy drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Teem Soda Water (50cl Pet)',
                'unit' => 'bottle',
                'cost_price' => 200.00,
                'selling_price' => 300.00,
                'stock_level' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Sparkling club soda mixer.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Chilled Nigerian Zobo Drink (50cl)',
                'unit' => 'bottle',
                'cost_price' => 300.00,
                'selling_price' => 500.00,
                'stock_level' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Natural chilled hibiscus drink infused with ginger.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'La Casera Apple Drink (50cl Pet)',
                'unit' => 'bottle',
                'cost_price' => 200.00,
                'selling_price' => 300.00,
                'stock_level' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Original carbonated apple drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Bigi Cola (60cl Pet)',
                'unit' => 'bottle',
                'cost_price' => 200.00,
                'selling_price' => 300.00,
                'stock_level' => 120,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Big quantity cola drink.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Aquafina Premium Table Water (75cl)',
                'unit' => 'bottle',
                'cost_price' => 150.00,
                'selling_price' => 250.00,
                'stock_level' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Pure drinking water.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Cway Purified Table Water (75cl)',
                'unit' => 'bottle',
                'cost_price' => 120.00,
                'selling_price' => 200.00,
                'stock_level' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Clean purified table drinking water.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => '5Alive Berry Blast Juice (78cl)',
                'unit' => 'bottle',
                'cost_price' => 800.00,
                'selling_price' => 1100.00,
                'stock_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'description' => 'Fruit juice blend with berry blast flavor.',
            ],
            [
                'category_id' => $mixers->id,
                'name' => 'Chivita 100% Real Orange Juice (1 Litre)',
                'unit' => 'pack',
                'cost_price' => 1100.00,
                'selling_price' => 1500.00,
                'stock_level' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Pure 100% real orange fruit juice.',
            ],
        ];

        $createdProducts = [];

        foreach ($catalog as $item) {
            $createdProducts[$item['name']] = Product::create([
                'category_id' => $item['category_id'],
                'vendor_id' => $vendor->id,
                'name' => $item['name'],
                'slug' => Str::slug($item['name'].'-'.$vendor->id),
                'description' => $item['description'],
                'image_url' => $item['image_url'],
                'unit' => $item['unit'],
                'cost_price' => $item['cost_price'],
                'selling_price' => $item['selling_price'],
                'stock_level' => $item['stock_level'],
                'is_global' => false,
                'is_active' => true,
                'is_chilled' => $item['is_chilled'] ?? true,
            ]);
        }

        // 4. Seed Initial Sample Order Linked Directly to Inventory
        $trophy = $createdProducts['Trophy Extra Quality Lager (600ml)'];
        $guinness = $createdProducts['Guinness Extra Stout (600ml)'];

        $orderSubtotal = (2 * $trophy->selling_price) + (1 * $guinness->selling_price);
        $deliveryFee = 500.00;

        $sampleOrder = Order::create([
            'user_id' => $consumer1->id,
            'vendor_id' => $vendor->id,
            'order_number' => 'BZ-DEMO9988',
            'status' => 'pending',
            'subtotal' => $orderSubtotal,
            'delivery_fee' => $deliveryFee,
            'total' => $orderSubtotal + $deliveryFee,
            'customer_name' => $consumer1->name,
            'customer_phone' => $consumer1->phone,
            'delivery_address' => 'Room 14, Executive Lodge, Gwallameji, Bauchi',
            'latitude' => 10.2847000,
            'longitude' => 9.7915000,
            'notes' => 'Please bring cold bottles!',
        ]);

        OrderItem::create([
            'order_id' => $sampleOrder->id,
            'product_id' => $trophy->id,
            'product_name' => $trophy->name,
            'quantity' => 2,
            'unit_price' => $trophy->selling_price,
            'subtotal' => 2 * $trophy->selling_price,
        ]);

        OrderItem::create([
            'order_id' => $sampleOrder->id,
            'product_id' => $guinness->id,
            'product_name' => $guinness->name,
            'quantity' => 1,
            'unit_price' => $guinness->selling_price,
            'subtotal' => 1 * $guinness->selling_price,
        ]);

        // Decrement stock for the sample order
        $trophy->decrement('stock_level', 2);
        $guinness->decrement('stock_level', 1);

        // 5. Seed Featured Party Bundles & Combo Packs
        $heineken = $createdProducts['Heineken Premium Lager (600ml)'] ?? null;
        $orijinBitters = $createdProducts['Orijin Herbal Bitters (75cl)'] ?? null;
        $fearlessRed = $createdProducts['Fearless Energy Drink - Red Berry (50cl)'] ?? null;
        $coke = $createdProducts['Coca-Cola Original (50cl Pet)'] ?? null;
        $carloRossi = $createdProducts['Carlo Rossi Sweet Red Wine (75cl)'] ?? null;

        if ($trophy && $guinness && $orijinBitters && $fearlessRed) {
            $bundle1 = PartyBundle::create([
                'vendor_id' => $vendor->id,
                'title' => '🎉 Gwallameji Weekend Vibes Combo',
                'slug' => 'gwallameji-weekend-vibes-combo',
                'description' => '4x Ice-Cold Trophy Lager + 2x Guinness Extra Stout + 1x Orijin Bitters (75cl). Perfect for hostel weekend chillouts!',
                'price' => 6800.00,
                'original_price' => 8100.00,
                'discount_percentage' => 16,
                'badge_text' => '🔥 SAVE 16% (STUDENT FAVOURITE)',
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ]);

            PartyBundleItem::create(['party_bundle_id' => $bundle1->id, 'product_id' => $trophy->id, 'quantity' => 4]);
            PartyBundleItem::create(['party_bundle_id' => $bundle1->id, 'product_id' => $guinness->id, 'quantity' => 2]);
            PartyBundleItem::create(['party_bundle_id' => $bundle1->id, 'product_id' => $orijinBitters->id, 'quantity' => 1]);

            $bundle2 = PartyBundle::create([
                'vendor_id' => $vendor->id,
                'title' => '⚡ All-Night Chaser Energy Pack',
                'slug' => 'all-night-chaser-energy-pack',
                'description' => '6x Fearless Red Berry Energy Drinks + 4x Coca-Cola Original + 2x Ice-Cold Trophy Lager.',
                'price' => 4200.00,
                'original_price' => 5300.00,
                'discount_percentage' => 20,
                'badge_text' => '⚡ 20% OFF (CHASER COMBO)',
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ]);

            PartyBundleItem::create(['party_bundle_id' => $bundle2->id, 'product_id' => $fearlessRed->id, 'quantity' => 6]);
            if ($coke) {
                PartyBundleItem::create(['party_bundle_id' => $bundle2->id, 'product_id' => $coke->id, 'quantity' => 4]);
            }
            PartyBundleItem::create(['party_bundle_id' => $bundle2->id, 'product_id' => $trophy->id, 'quantity' => 2]);

            if ($carloRossi && $heineken) {
                $bundle3 = PartyBundle::create([
                    'vendor_id' => $vendor->id,
                    'title' => '🍾 VIP Hostel Celebration Bundle',
                    'slug' => 'vip-hostel-celebration-bundle',
                    'description' => '2x Carlo Rossi Sweet Red Wine (75cl) + 6x Chilled Heineken Premium Lager.',
                    'price' => 17500.00,
                    'original_price' => 20200.00,
                    'discount_percentage' => 13,
                    'badge_text' => '👑 VIP CELEBRATION',
                    'image_url' => 'https://images.unsplash.com/photo-1558001373-7b9fcc48fac0?auto=format&fit=crop&w=600&q=80',
                    'is_active' => true,
                ]);

                PartyBundleItem::create(['party_bundle_id' => $bundle3->id, 'product_id' => $carloRossi->id, 'quantity' => 2]);
                PartyBundleItem::create(['party_bundle_id' => $bundle3->id, 'product_id' => $heineken->id, 'quantity' => 6]);
            }
        }
    }
}
